//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndOneConstructions.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.ConstructionSites = new HashSet<ConstructionSite>();
        }
    
        public int AddressId { get; set; }
        public string Details { get; set; }
        public int TownId { get; set; }
    
        public virtual Town Town { get; set; }
        public virtual ICollection<ConstructionSite> ConstructionSites { get; set; }
    }
}
