//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndOneConstructions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int BuildingId { get; set; }
        public string Name { get; set; }
        public int ConstructionSiteId { get; set; }
    
        public virtual ConstructionSite ConstructionSite { get; set; }
    }
}
