//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndOneConstructions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ConstructionSites = new HashSet<ConstructionSite>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int ProjectId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<ConstructionSite> ConstructionSites { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
